<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: api/proto/countries.proto

namespace Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>proto.CountryList</code>
 */
class CountryList extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .proto.Country countries = 1;</code>
     */
    private $countries;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Proto\Country[] $countries
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Api\Proto\Countries::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .proto.Country countries = 1;</code>
     * @return RepeatedField<\Proto\Country>
     */
    public function getCountries()
    {
        return $this->countries;
    }

    /**
     * Generated from protobuf field <code>repeated .proto.Country countries = 1;</code>
     * @param \Proto\Country[] $var
     * @return $this
     */
    public function setCountries($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Proto\Country::class);
        $this->countries = $arr;

        return $this;
    }

}

