<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: api/proto/countries.proto

namespace GPBMetadata\Api\Proto;

class Countries
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            "\x0A\x99\x01\x0A\x19api/proto/countries.proto\x12\x05proto\";\x0A\x07Country\x12\x0C\x0A\x04name\x18\x01 \x01(\x09\x12\x12\x0A\x0Aalpha2Code\x18\x02 \x01(\x09\x12\x0E\x0A\x06region\x18\x03 \x01(\x09\"0\x0A\x0BCountryList\x12!\x0A\x09countries\x18\x01 \x03(\x0B2\x0E.proto.Countryb\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

